pipelines:
    tools:
        branches:
            patterns:
                feature: .+
    branches:
        feature:
            steps:
                - golang:
                      - glide:
                      - test:
                            binary: ginkgo
                            gatherJunit: true
                      - build:
                            mainPath: cmd/app/main.go
                            outFile: publish/app
                            env:
                                GOOS: darwin
                                GOARCH: amd64